trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- script: |
    echo ===== ROOT =====
    dir
    echo ===== FIND PACKAGE.JSON =====
    dir /s package.json
    echo ===== FIND VITE CONFIG =====
    dir /s vite.config.*
  displayName: Find React Project

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: |
    npm install
    npm run build
  displayName: Build React App